// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apteka.Data;

#nullable disable

namespace apteka.Migrations
{
    [DbContext(typeof(ApplicationDbContext2))]
    [Migration("20260311103112_q5")]
    partial class q5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("apteka.Models.Akqia", b =>
                {
                    b.Property<int>("IDAk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDAk"));

                    b.Property<string>("Naz")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Pr")
                        .HasColumnType("int");

                    b.HasKey("IDAk");

                    b.ToTable("Akqias");
                });

            modelBuilder.Entity("apteka.Models.Lek", b =>
                {
                    b.Property<int>("IDL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDL"));

                    b.Property<int?>("AkqiaIDAk")
                        .HasColumnType("int");

                    b.Property<int>("IDAk")
                        .HasColumnType("int");

                    b.Property<int>("IDPr")
                        .HasColumnType("int");

                    b.Property<int>("IDVZ")
                        .HasColumnType("int");

                    b.Property<int?>("LekIDL")
                        .HasColumnType("int");

                    b.Property<string>("Naz")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ProizIDPr")
                        .HasColumnType("int");

                    b.Property<int>("Qena")
                        .HasColumnType("int");

                    b.Property<int?>("VidZIDV")
                        .HasColumnType("int");

                    b.HasKey("IDL");

                    b.HasIndex("AkqiaIDAk");

                    b.HasIndex("LekIDL");

                    b.HasIndex("ProizIDPr");

                    b.HasIndex("VidZIDV");

                    b.ToTable("Leks");
                });

            modelBuilder.Entity("apteka.Models.Proiz", b =>
                {
                    b.Property<int>("IDPr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPr"));

                    b.Property<string>("Naz")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDPr");

                    b.ToTable("Proizs");
                });

            modelBuilder.Entity("apteka.Models.Role", b =>
                {
                    b.Property<int>("idRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idRole"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idRole");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("apteka.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdUser");

                    b.HasIndex("IdRole");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("apteka.Models.VidZ", b =>
                {
                    b.Property<int>("IDV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDV"));

                    b.Property<string>("Naz")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDV");

                    b.ToTable("Vids");
                });

            modelBuilder.Entity("apteka.Models.ZakLek", b =>
                {
                    b.Property<int>("IDZL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDZL"));

                    b.Property<int>("IDL")
                        .HasColumnType("int");

                    b.Property<int>("IDZ")
                        .HasColumnType("int");

                    b.Property<int?>("lekIDL")
                        .HasColumnType("int");

                    b.HasKey("IDZL");

                    b.HasIndex("IDL");

                    b.HasIndex("lekIDL");

                    b.ToTable("ZakLeks");
                });

            modelBuilder.Entity("apteka.Models.Zakaz", b =>
                {
                    b.Property<int>("IDZ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDZ"));

                    b.Property<DateTime>("Data")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsersIdUser")
                        .HasColumnType("int");

                    b.HasKey("IDZ");

                    b.HasIndex("UsersIdUser");

                    b.ToTable("Zakazs");
                });

            modelBuilder.Entity("apteka.Models.Lek", b =>
                {
                    b.HasOne("apteka.Models.Akqia", "Akqia")
                        .WithMany("Leks")
                        .HasForeignKey("AkqiaIDAk");

                    b.HasOne("apteka.Models.Lek", null)
                        .WithMany("Leks")
                        .HasForeignKey("LekIDL");

                    b.HasOne("apteka.Models.Proiz", "Proiz")
                        .WithMany("Leks")
                        .HasForeignKey("ProizIDPr");

                    b.HasOne("apteka.Models.VidZ", "VidZ")
                        .WithMany("Leks")
                        .HasForeignKey("VidZIDV");

                    b.Navigation("Akqia");

                    b.Navigation("Proiz");

                    b.Navigation("VidZ");
                });

            modelBuilder.Entity("apteka.Models.User", b =>
                {
                    b.HasOne("apteka.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("apteka.Models.ZakLek", b =>
                {
                    b.HasOne("apteka.Models.Zakaz", "zakaz")
                        .WithMany("ZakLeks")
                        .HasForeignKey("IDL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apteka.Models.Lek", "lek")
                        .WithMany()
                        .HasForeignKey("lekIDL");

                    b.Navigation("lek");

                    b.Navigation("zakaz");
                });

            modelBuilder.Entity("apteka.Models.Zakaz", b =>
                {
                    b.HasOne("apteka.Models.User", "Users")
                        .WithMany("Zakazs")
                        .HasForeignKey("UsersIdUser");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("apteka.Models.Akqia", b =>
                {
                    b.Navigation("Leks");
                });

            modelBuilder.Entity("apteka.Models.Lek", b =>
                {
                    b.Navigation("Leks");
                });

            modelBuilder.Entity("apteka.Models.Proiz", b =>
                {
                    b.Navigation("Leks");
                });

            modelBuilder.Entity("apteka.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("apteka.Models.User", b =>
                {
                    b.Navigation("Zakazs");
                });

            modelBuilder.Entity("apteka.Models.VidZ", b =>
                {
                    b.Navigation("Leks");
                });

            modelBuilder.Entity("apteka.Models.Zakaz", b =>
                {
                    b.Navigation("ZakLeks");
                });
#pragma warning restore 612, 618
        }
    }
}
